### ISSUE TITLE
Ornate Mirror 2nd turn CTD

### ISSUE THREAD

**Issue by 34N15H** [twanvl/sts-conspire#2]
I'm getting a crash on the start of my second turn in a fight against the Ornate Mirror boss. The Crash log looks like this:

12:48:48.611 INFO basemod.BaseMod> ----------- Minion Before Attacking --------------
Final damage: 35
12:48:49.297 INFO basemod.BaseMod> publish on post power apply
12:48:49.297 INFO basemod.BaseMod> powers modified
12:48:49.463 INFO basemod.BaseMod> publishPreMonsterTurn
Exception: java.lang.NullPointerException
12:48:49.798 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
	at conspire.monsters.MirrorImage.applyFlipToSkeleton(MirrorImage.java:121) ~[Conspire.jar:?]
	at conspire.monsters.MirrorImage.render(MirrorImage.java:91) ~[Conspire.jar:?]
	at com.megacrit.cardcrawl.monsters.MonsterGroup.render(MonsterGroup.java:385) ~[?:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.render(AbstractRoom.java:548) ~[?:?]
	at com.megacrit.cardcrawl.rooms.MonsterRoom.render(MonsterRoom.java:99) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.render(AbstractDungeon.java:2656) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:479) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
Controllers: removed manager for application, 0 managers active
Game closed.

Also, this boss currently deals 50% of damage it takes back on the start of the next turn. So unless you have 
a) healing
b) a way to block at the start of your turn
c) more than half of its max hp
d) lots of attacks that only deal one damage(?)
you can't win.
Seems balanced! : D (If I'm overlooking something here I apologize in advance.)

**Comment by twanvl** [comment]
What character were you playing as when that crash took place?

Regarding the balance: Ornate Mirror deals 50% of the damage it takes back at the start of *its* turn, so you will still have your block by then. Maybe I should word it as "Whenever it takes damage, deals 50% of the damage back at the start of its turn"? Do you have any suggestions to make it more clear?

**Comment by 34N15H** [comment]
I was playing as the Construct. If you just change the "next turn" to "at the start of its turn" in the tooltip that should prevent any misunderstandings. I was also playing in SuperFastMode though so it just *looked* like it happened at the start of my turn. Here's a list of all the mods I currently have installed, just in case:
BaseMod
SuperFastMod
FetchMod
StSLib
Friendly Minions
Always Whale
Shop Mod
Mimic Mod
Spikes Relics
Infinite Spire
Conspire
Blakk Mod
Hubris
Replay The Spire
Beaked The Cultist
The Construct
Mad Scientist
The Blackbeard Mod
The Disciple
The Mystic
The Witch
Colored Map
